### ISSUE TITLE
Consistent Element Name - Case

### ISSUE THREAD

**Issue by huberrob** [rdawg-pidinst/schema#14] opened 2019-02-22 16:47 UTC
This should be harmonized. In particular capitalization e.g.:

RelatedIdentifier vs relatedIdentifierType

**Comment by RKrahl** [comment] 2019-02-26 12:31
There is a system in the capitalization that you might have missed: names of main properties start with a capital letter, names of subproperties start with lowercase. This scheme follows the model from DataCite.

**Comment by huberrob** [comment] 2019-02-27 12:05
OK thanks..

**Comment by RKrahl** [comment] 2019-02-27 12:12
Now this is unfortunate: i just closed #16 as a duplicate of this one. Shortly after, you closed this issue. I'll reopen just in case @kitchenprinzessin3880 wants to comment.

**Comment by RKrahl** [comment] 2021-02-26 14:26
I guess this has been settled by now.  I suggest to close.

**Closed as completed** 2021-03-01 08:23 UTC
